### ISSUE TITLE
Look into Rest Recovery integration

### ISSUE THREAD

**Issue by PwQt** [PwQt/magic-items-2#153]
Take a look how would Rest-Recovery integration work

**Comment by roth-michael** [comment]
Hi! As Rest Recovery's current dev I’m thinking we can work together on what the best solution here is. From a cursory look at your code, I think I might have an idea of why rest recovery is currently breaking it, and of how it could be solved. Gonna play around with it today to make sure I’m right.

**Comment by roth-michael** [comment]
Right: So essentially Rest Recovery hooks `dnd5e.preShortRest` and `dnd5e.preLongRest`, returns `false`, and directly calls `actor._rest` itself with appropriate config. Think there's two potentially good ways to go about this:
1. If your `onShortRest`/`onLongRest` functions are exposed, on my side, I can check if magic items is installed and active, and if so call them after or during the rest execution.
2. Perhaps more work on your end and I'm not sure if it would break anything for you, but you could, instead of overriding rest functions, hook onto `dnd5e.restCompleted`, which passes `actor` and `results` (and `results` should still have the `newDay` (and I believe also `longRest`) property.

Let me know your thoughts!

**Comment by PwQt** [comment]
I think the quicker way to do it is for me to make some API methods for `onShort/LongRest`, I'll look into that in the next couple of days and try to implement it.

**Comment by PwQt** [comment]
I've created an API methods, please verify if that's what is required of me, inside of this branch: https://github.com/PwQt/magic-items-2/tree/153-look-into-rest-recovery-integration

**Comment by roth-michael** [comment]
I think the second ones should work as expected, as long as calling those functions indeed do the item recharge properly. I'm testing just calling them manually and it doesn't seem to be working on my end, but it may just be an issue on my side.

**Comment by roth-michael** [comment]
Ignore that last message: That was just me being dumb using your module incorrectly lol. Yes: The second set (`execActorRestUnderHood` ones) will be perfect.

**Comment by PwQt** [comment]
https://github.com/PwQt/magic-items-2/blob/master/wiki/api.md please consult this doc for the new implementation - I'll release that in next version, most likely this week.
