### ISSUE TITLE
The Magic Item module Issue

### ISSUE THREAD

**Issue by Beybee** [PwQt/magic-items-2#200]
The module is currently not working on the current version of foundary :'( do you know when it will work?

**Comment by PwQt** [comment]
Do you mean D&D 4.x version? It should be working on latest v12 version.

If D&D 4.x - please follow this task: https://github.com/PwQt/magic-items-2/issues/180 or check the MI Discord for latest updates - I had some life situations that made my life not really think about developing the module.

tl:dr; 
- I am going to rewrite the charges to use the ones present in the item instead of in the "Magic Item" tab.
- After that I'll check whether the module will be moved to 4.1, since 4.1 supports "items with spells" from the get-go.

**Comment by Beybee** [comment]
![image](https://github.com/user-attachments/assets/6453a82d-66ca-425c-8304-282d394ebac1)

**Comment by Beybee** [comment]
Anytime I try to activate the module, I am geting this message.
